/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "dell_wb3023"
      pixel_format: "mjpeg2rgb"
      color_format: "yuv420p"
      # av_device_format: "YUV420P"
      image_width: 1920
      image_height: 1080
      camera_name: "dell_wb3023"
      # reusing same camera intrinsics only for demo, should really be unique for camera2"
      # camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1