/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "insta360_x4"
      pixel_format: "mjpeg2rgb"
      av_device_format: "YUV420P"
      image_width: 2880
      image_height: 1440
      camera_name: "insta360_x4"
      # camera_info_url: "package://usb_cam/config/camera_info.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: false
      focus: -1