/**:
    ros__parameters:
      video_device: "/dev/video2"
      framerate: 20.0
      io_method: "mmap"
      frame_id: "logitech_c920_1"
      pixel_format: "mjpeg2rgb"
      av_device_format: "YUV422P"
      image_width: 1920
      image_height: 1080
      camera_name: "logitech_c920_1"
      camera_info_url: "package://bev_cameras/config/logitech_c920_camera_info_0.yaml"
      brightness: -1
      contrast: -1
      saturation: -1
      sharpness: -1
      gain: -1
      auto_white_balance: true
      white_balance: 4000
      autoexposure: true
      exposure: 100
      autofocus: true
      focus: -1