start_service_name: "start_capture" # Defines name suffix for std_srvs::Empty service which restarts suspended streaming
stop_service_name: "stop_capture"   # Defines name suffix for std_srvs::Empty service which suspends camera polling timer

video_device: /dev/video2           # Device driver's entrypoint
io_method: mmap                     # I/O method
                                    # - read - for devices supporting virtual filesystem or block I/O
                                    # - mmap - for devices with direct libusb memory mapping
                                    # - userptr - for userspace devices supporting userspace pointer exchange

# Supported pixel format + color format: mjpeg + yuv420p
pixel_format: mjpeg
color_format: yuv420p
create_suspended: false             # Instructs the node whether to start streaming immediately after launch
                                    # or to wait until the start service will be triggered
full_ffmpeg_log: false              # Allows to suppress warning messages generated by libavcodec, cleans log
camera_name: dell_camera            # ROS internal name for the camera, used to generate camera_info message
camera_frame_id: dell_camera        # Frame ID used to generate coordinate transformations
camera_transport_suffix: image_raw  # Suffix used by image_transport to generate topic names
camera_info_url: ""                 # URI for camera calibration data (likely a YML file obtained from camera_calibration)

# Supported resolution: 640x480, 1280x720, 1920x1080, 2560x1440
image_width: 2560
image_height: 1440
# Camera polling frequency, Hz (integer). Supported frame rate: 30
framerate: 30                     

# Auxiliary camera parameters provided by libv4l2.
    # Names for these parameters are generated automatically according to the intrinsic control names exported by the
    # camera driver. The node queries camera's kernel controller module to determine the parameters that can be set up
    # via ROS. For these parameters the corresponding ROS parameters with identical names are generated under this
    # namespace.
    # See also the comprehensive node output describing parameter names and feasible values for them to be set up here.
    # It is also possible to have a list of the available control names using v4l2-ctl application from v4l2-util package:
    # v4l2-ctl --device=/dev/video<ID> -L
intrinsic_controls:                 
    focus_auto: true
    exposure_auto_priority: true
    exposure_auto: 3
    white_balance_temperature_auto: true
    power_line_frequency: 60
    ignore: [
        brightness,
        contrast,
        saturation,
        gain,
        sharpness,
        backlight_compensation,
        white_balance_temperature,
        exposure_absolute,
        pan_absolute,
        tilt_absolute,
        focus_absolute,
        zoom_absolute
    ]                               # Use this list to enumerate the control names that should be delisted from the camera setup
                                    # NOTE: the ROS parameters for the V4L controls supported but listed here would be STILL
                                    # generated, but the values WILL NOT BE USED to set up the camera. To affect these controls
                                    # once you want to do that, their names should me REMOVED from this list!

